name: Deploy to SmarterASP.NET

on:
  release:
      types: [published]
      
jobs:
  deploy:
    runs-on: windows-latest  # Necessário para Web Deploy

    environment: 
      name: secrets
    env:
      work-directory: Codigo/Frota/FrotaWeb

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Altere para a versão do .NET do seu projeto

    - name: Restore Dependencies
      run: |
        cd ${{env.work-directory}}
        dotnet restore
    - name: Build
      run: |
        cd ${{env.work-directory}}
        dotnet build --configuration Release --no-restore
    - name: Replace variables in appsettings.json
      uses: microsoft/variable-substitution@v1
      with:
        files: '${{env.work-directory}}/appsettings.json'
      env:
        ConnectionStrings.FrotaDatabase: ${{ secrets.CONNECTION_STRING }}

    - name: Publish
      run: |
        cd ${{env.work-directory}}
        dotnet publish -c Release -o ./publish
        
    - name: Install Web Deploy
      run: |
        choco install webdeploy -y --force
        $webDeployPath = "${env:ProgramFiles}\IIS\Microsoft Web Deploy V3\msdeploy.exe"
        if (-not (Test-Path $webDeployPath)) {
            Write-Error "MSDeploy installation failed!"
            exit 1
        }

    - name: Deploy to SmarterASP.NET via MSDeploy
      run: |
        cd ${{env.work-directory}}
        & "${env:ProgramFiles}\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:contentPath='./publish' -dest:contentPath='frotaweb',ComputerName='https://win8184.site4now.net:8172/msdeploy.axd?site=itetech-001-site5',UserName='itetech-001',Password='${{ secrets.FTP_PASS_WEB }}',AuthType='Basic' -allowUntrusted
        exit $LASTEXITCODE
