name: Deploy on Release

on:
  release:
    types: [published]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Set up dependency caching for faster builds
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
            
      - name: Build with dotnet
        run: dotnet build --configuration Release
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.CONNECTION_STRING }}

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.CONNECTION_STRING }}

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER_WEB }}
          password: ${{ secrets.FTP_PASS_WEB }}
          local-dir: ${{env.DOTNET_ROOT}}/myapp/
          server-dir: 'frotaweb/'
