name: Deploy to SmarterASP.NET

on:
  release:
      types: [published]
      
jobs:
  deploy:
    runs-on: windows-latest  # Necessário para Web Deploy

    environment: 
      name: secrets
    env:
      work-directory: Codigo/Frota/FrotaWeb

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Altere para a versão do .NET do seu projeto

    - name: Restore Dependencies
      run: |
        cd ${{env.work-directory}}
        dotnet restore
    - name: Build
      run: |
        cd ${{env.work-directory}}
        dotnet build --configuration Release --no-restore
    - name: Replace variables in appsettings.json
      uses: microsoft/variable-substitution@v1
      with:
        files: '${{env.work-directory}}/appsettings.json'
      env:
        ConnectionStrings.FrotaDatabase: ${{ secrets.CONNECTION_STRING }}

    - name: Publish
      run: |
        cd ${{env.work-directory}}
        dotnet publish -c Release -o ./publish
        
    - name: Deploy to SmarterASP.NET
      uses: MsDeployAllTheThings/msdeploy-action@v1.1
      with:
        webSiteName: 'itetech-001-site5'
        computerName: 'https://win8184.site4now.net:8172/msdeploy.axd?site=itetech-001-site5'
        username: 'itetech-001'
        password: ${{ secrets.FTP_PASS_WEB }}
        sourcePath: './publish'
        destinationPath: 'frotaweb'
