name: Deploy to SmarterASP.NET

on:

  release:
      types: [published]

jobs:

  deploy:
  
    runs-on: windows-latest

    environment: 
      name: secrets
  
    steps:
      - name: Checkout code
      
        uses: actions/checkout@v4
      
      - name: Setup .NET
      
        uses: actions/setup-dotnet@v3
      
        with:
          dotnet-version: '8.0.x'  # adjust to the user's version
      
      - name: Build project
      
        run: dotnet build --configuration Release
      
      - name: Publish using Web Deploy
      
        uses: warrenbuckley/WebDeploy-Action@v1
      
        with:
      
          websiteName: itetech-001-site5
      
          username: ${{ secrets.FTP_USER_WEB }}
          
          password: ${{secrets.FTP_PASS_WEB }}
          
          server: https://win8184.site4now.net:8172/msdeploy.axd
          
          sourcePath: './frotaweb'
