name: Frota-WEB CI

on:
  release:
    types: [published] 

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    environment:
      name: production 

    env:
      work-directory: Codigo/Frota/FrotaWeb

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup .NET version
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
      
    - name: Replace variables in appsettings.json
      uses: microsoft/variable-substitution@v1
      with:
        files: '${{env.work-directory}}/appsettings.json'
      env:
        ConnectionStrings.FrotaDatabase: ${{ secrets.CONNECTION_STRING }}

    - name: Restore dependencies
      run: |
        cd ${{env.work-directory}}
        dotnet restore

    - name: Build Application
      run: |
        cd ${{env.work-directory}}
        dotnet build --no-restore
      
    - name: Publish Application
      run: |
        cd ${{env.work-directory}}
        dotnet publish --configuration Release --no-restore --output ./frotaweb
    
    - name: Upload via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER_WEB }}
        password: ${{ secrets.FTP_PASS_WEB }}
        local-dir: '${{env.work-directory}}/frotaweb/'  
        server-dir: '/'  
        exclude: |
          **/.git*
          **/.git*/**
          **/AnaliseProjeto


